### ISSUE TITLE
it shows the details from tomorrow?

### ISSUE THREAD

**Issue by tntradio** [xiaoerge/LittleAstro-API#2]
https://api.littleastro.com/public/xiaoerge_dev_horoscope.php

**Comment by xiaoerge** [comment]
No,  today.

**Comment by tntradio** [comment]
What TimeZone is using the page? Because I see right now "{"table":"Horoscope_Reading","query":"SELECT *\nFROM `Horoscope_Reading`\n LIMIT 20","data":[{"Sign":"Aries","Daily_Horoscope":"You may feel a bit restless because you know something is brewing but can't seem to get hold of it, Aries. This energy is like a river rushing beneath your feet while you stand on a bridge. The water is tempting, yet you can't summon up the courage to jump in. Don't feel like you have to be a part of everything. Perhaps your destiny lies on the other side of the bridge.","Weekly_Horoscope":"The full moon at the start of the week could encourage you to drop what you\u009d\u009d\u009dre doing and go off on an adventure."
And the real today text from the website it's another one:  "May 30, 2018 - There is power in your words today, and a great deal of emotional self-confidence, Aries. Things may be moving quite rapidly, but you certainly have the strength and swiftness of mind to keep up. There are great opportunities waiting if you do, especially when you team up with others. Attend a party or any sort of social gathering where you can proudly display your elegant attire to the crowd."
As you can see the information is from: "May 31, 2018 - You may feel a bit restless because you know something is brewing but can't seem to get hold of it, Aries. This energy is like a river rushing beneath your feet while you stand on a bridge. The water is tempting, yet you can't summon up the courage to jump in. Don't feel like you have to be a part of everything. Perhaps your destiny lies on the other side of the bridge."

**Comment by tntradio** [comment]
I tried it at different hours from my timezone, but same thing happens..

**Comment by xiaoerge** [comment]
Database updates at Pacific timezone.   API call does not take in timezone parameter.
